# Site settings
title: RNGDES
subtitle:
email: rngdes.stream@gmail.com
description: Variety streamer. Gamer. Designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rngdes.github.io" # the base hostname & protocol for your site
author: Anthony Nguyen
street_address:
city: 
state: 
zip_code: 
country:
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/rngdes
twitch_url: https://twitch.tv/rngdes
youtube_url:

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed